name: Build on Ubuntu

on:
  push:
    branches:
      - master
      - develop
      - v*

    tags:
      - v*

  pull_request:
    paths:
      - cmake/**
      - src/**
      - CMakeLists.txt
      - .github/**

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        buildtype: [Release]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: >
        sudo apt-get update && sudo apt-get install cmake build-essential
        libgmp-dev zip libsdl2-dev

    - name: Prepare build Environment
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} ..

    - name: Build
      run: |
        cd build
        make -j `nproc`

    - name: Prepare datapack contents
      shell: bash
      run: |
        cd ..
        zip -r The-Forgotten-Client.zip The-Forgotten-Client

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: The-Forgotten-Client-${{ matrix.os }}-${{ github.sha }}
        path: ${{ runner.workspace }}/The-Forgotten-Client.zip
